### ISSUE TITLE
In survey summary page under Scheduling section do the following change.

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#121]
In survey summary page under Scheduling section do the following change.

The main page should read as follows, not as in the screen grab below. One button that reads “Create Survey Schedule”

![image](https://cloud.githubusercontent.com/assets/26476914/26309889/6f896454-3f1c-11e7-9fc3-4af7fc7929be.png)

**Comment by veereshms** [comment]
2).	The word Schedule should be used, not scheduler as below
![image](https://cloud.githubusercontent.com/assets/26476914/26309942/9dc3cdbe-3f1c-11e7-85ec-7a3f84222e64.png)

**Comment by kishanOPG** [comment]
Dev fixed

**Comment by kishanOPG** [comment]
Fixed

**Comment by onepointpb** [comment]
The Scheduler is changed to Schedule. Then "List of Scheduler" should also be changed to "List of Schedules".

**Comment by onepointpb** [comment]
It is not fixed. 
Also, when I was trying to create a new schedule the Save button did not work. After sometime the page got disturbed (please refer the screenshot below). Then on clicking Save multiple times it got redirected to Login screen.
![schedule](https://user-images.githubusercontent.com/26476815/27023359-cb590e0c-4f6f-11e7-99e7-306369802bb1.png)

**Comment by deepika-Gopala** [comment]
please try again for the above scenario, the server was down previously and even adminsuite.staging dint work for last 5 mins.

Thanks.

**Comment by onepointpb** [comment]
I am not facing the issue now.
But the above text changes are not fixed.

**Comment by onepointraj** [comment]
fixed in dev

**Comment by veereshms** [comment]
Verified.
