### ISSUE TITLE
Delete project message need correction

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#263]
In delete project message add following generic message "Are you sure, you want to delete selected project(s)?" so that it is consistent with messages in other modules.

![image](https://user-images.githubusercontent.com/26476914/28820115-1596fada-76ce-11e7-8cef-a3fb7a60278f.png)

**Comment by deepika-Gopala** [comment]
It was mentioned by tim in some of the previous bug to mention the project name. Hence its placed.

**Comment by onepointpb** [comment]
1. If you want to keep the name of the project/survey then change the text to match it. 
2. Also consider the text for multiple project/survey delete.
But the above alert text is not matching accordingly.

**Comment by deepika-Gopala** [comment]
3. After Deleting the Project , immediate delete of multiple surveys is not working , the pop up doesnt close.

**Comment by premonepoint** [comment]
fixed

**Comment by veereshms** [comment]
3) After deleting the project the page is getting refreshed twice (progress dialog) which is not looking good.
4) Selection count still not getting reset after moving to different projects items

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
