### ISSUE TITLE
In media module for video upload preview is not working properly after uploading the file, it is getting displayed as a image

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#95]
In media module for video upload preview is not working properly after uploading the file, it is getting displayed as a image. Kindly refer attached screenshot.
![video upload](https://cloud.githubusercontent.com/assets/26476914/26152404/6e5d1fc2-3b24-11e7-9e0b-a1ee24263e9e.jpg)

**Comment by onepointpb** [comment]
This is happening for .mov and .mp4 format.

**Comment by premonepoint** [comment]
Fixed
Expect HTML 5 Video player doesn't not support  .webm format i

**Comment by veereshms** [comment]
For video upload preview is coming only to .mp4 format file, as per details given by you it should support following .avi,.mp4,.mov,.wmv,.3gb. And also while uploading video file chooser is set to display only .avi, .mp4 and .wmv files

**Comment by premonepoint** [comment]
Fixed in dev

**Comment by veereshms** [comment]
File chooser is still not showing all supported file formats, fix this issue for create new media and as well as edit media.

Below are the screenshots of file chooser

Image:

Audio:

Video:


Below screenshots shows file which i am using for testing,

Image:
![image](https://user-images.githubusercontent.com/26476914/27426119-4160b81c-5758-11e7-91ae-3c10ba2db1ab.png)

Audio:
![image](https://user-images.githubusercontent.com/26476914/27426146-5a888720-5758-11e7-9db8-55fd814d5cff.png)

Video:
![image](https://user-images.githubusercontent.com/26476914/27426178-6bfac798-5758-11e7-8cba-745457824cb2.png)

**Comment by deepika-Gopala** [comment]
As discussed ,

For media , we are currently allowing only specific file types. In this case  jpeg option will be added form image type..
Where as for audio and video currently we are allowing only  mp3 and  MP4,.WEBM   respectively for the present release

**Comment by veereshms** [comment]
File filter is different for create new media and edit new media, while creating new media it shows only those files which you said are valid but in edit media if we browse to upload a file it show all files (audio, video and image) irrespective of file formats.

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
